### ISSUE TITLE
ci: isort config is not compatible with black

### ISSUE THREAD

**Issue by Ab2nour** [Ab2nour/analyse-survie#19]
Currently, we use the default isort configuration (done by @jExbrayat)

However, by default, the isort configuration is not compatible with black.
We should set the configuration of isort to be compatible with black.
(it is clearly written in the docs https://pycqa.github.io/isort/docs/configuration/black_compatibility.html )

 Please @jExbrayat, can you fix this?

Solution:
<details>
<summary>Click here to reveal the solution...</summary>

The pyproject.toml should be modified, to add an entry for isort configuration.
It should look like this:

```toml
[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^23.10.0"}
isort = "^5.12.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

We added these two lines:
```toml
[tool.isort]
profile = "black"
```
</details>
